import type { Metadata } from "next";
import { languageAlternates } from "../localized-metadata";
import { Arrow, SiteFooter, SiteHeader } from "../components/SiteChrome";
import { Localized } from "../components/LanguageContext";
import { ContactForm } from "../components/ContactForm";

export const metadata: Metadata = { title: "Plan a Building IoT Pilot — Blutech", description: "Plan a practical building AI and IoT pilot with the Blutech project team.", alternates:{canonical:"/contact",languages:languageAlternates("/contact")} };

export default function ContactPage(){return <main className="internal-page"><SiteHeader/><section className="contact-page"><div className="contact-lead"><p className="eyebrow light"><Localized en="PLAN A PILOT" tc="規劃試點" sc="规划试点" ar="خطط لتجربة" /></p><h1><Localized en="Start with the building—not the gadget." tc="由建築需要開始，而不是由設備開始。" sc="从建筑需要开始，而不是从设备开始。" ar="ابدأ بالمبنى، لا بالجهاز." /></h1><p><Localized en="Tell us what the property team needs to see, prevent or improve. We will help shape a measurable first scope." tc="告訴我們物業團隊需要看見、預防或改善甚麼，我們會協助制定可量度的第一階段範圍。" sc="告诉我们物业团队需要看见、预防或改善什么，我们会协助制定可衡量的第一阶段范围。" ar="أخبرنا بما يحتاج فريق العقار إلى رؤيته أو منعه أو تحسينه، وسنساعد في صياغة نطاق أول قابل للقياس." /></p></div><div className="contact-card"><span><Localized en="PROJECT ENQUIRIES" tc="項目查詢" sc="项目咨询" ar="استفسارات المشاريع" /></span><a href="mailto:enquiry@blutech.io">enquiry@blutech.io <Arrow/></a><div><p><Localized en="Useful details to include" tc="建議提供的資料" sc="建议提供的资料" ar="تفاصيل مفيدة" /></p><ul><li><Localized en="Property type and location" tc="物業類型與地點" sc="物业类型与地点" ar="نوع العقار وموقعه" /></li><li><Localized en="Operational problem or design objective" tc="營運問題或設計目標" sc="运营问题或设计目标" ar="المشكلة التشغيلية أو هدف التصميم" /></li><li><Localized en="Target area, floor or portfolio" tc="目標區域、樓層或物業組合" sc="目标区域、楼层或物业组合" ar="المنطقة أو الطابق أو المحفظة المستهدفة" /></li><li><Localized en="Existing BMS, network or IoT systems" tc="現有 BMS、網絡或 IoT 系統" sc="现有 BMS、网络或 IoT 系统" ar="أنظمة BMS أو الشبكة أو IoT القائمة" /></li><li><Localized en="Desired pilot or project timing" tc="期望試點或項目時間" sc="期望试点或项目时间" ar="التوقيت المطلوب للتجربة أو المشروع" /></li></ul></div><small>Hong Kong · Dongguan R&amp;D · Qatar</small></div></section><section className="contact-form-section section-pad"><div className="catalogue-heading"><div><p className="section-label"><Localized en="Project brief" tc="項目資料" sc="项目资料" ar="موجز المشروع" /></p><h2><Localized en="Give us the context." tc="告訴我們現場背景。" sc="告诉我们现场背景。" ar="شاركنا سياق الموقع." /></h2></div><p><Localized en="A clear first brief helps us propose the right sensing, software, integration and delivery path." tc="清晰的初步資料有助我們提出合適的感測、軟件、整合及交付路徑。" sc="清晰的初步资料有助我们提出合适的感知、软件、集成及交付路径。" ar="يساعدنا الموجز الواضح على اقتراح مسار الاستشعار والبرمجيات والتكامل والتنفيذ المناسب." /></p></div><ContactForm/></section><section className="contact-route"><p><Localized en={<>For product submittals, consultant specifications or integration workshops, reference the relevant model—such as <strong>BT102</strong>—and the project stage in your email.</>} tc={<>如需產品提交文件、顧問規格或整合工作坊，請在電郵列明相關型號（例如 <strong>BT102</strong>）及項目階段。</>} sc={<>如需产品提交文件、顾问规格或集成工作坊，请在邮件列明相关型号（例如 <strong>BT102</strong>）及项目阶段。</>} ar={<>لطلب مستندات المنتج أو مواصفات الاستشاري أو ورشة تكامل، اذكر الطراز المعني مثل <strong>BT102</strong> ومرحلة المشروع.</>} /></p></section><SiteFooter/></main>}
