import type { Metadata } from "next";
import { languageAlternates } from "../localized-metadata";
import { Arrow, PageCta, SiteFooter, SiteHeader } from "../components/SiteChrome";
import { toSimplified } from "../project-localization";

export const metadata: Metadata = { title: "Building IoT Resources — Blutech", description: "Practical guides for owners, property teams, architects and consultants planning building AI and IoT projects.", alternates:{canonical:"/resources",languages:languageAlternates("/resources")} };

const resourcesEn = [["OWNER BRIEF","How to define a smart-building pilot that can prove value","Frame one outcome, a dependable baseline and a scale decision before selecting devices."],["PROPERTY OPERATIONS","What a useful building dashboard should show","Separate status, attention and action so teams do not have to interpret raw telemetry."],["DESIGN & CONSULTANCY","A privacy-first sensing checklist","Match the signal to the space, define what is never collected and document where processing happens."],["RETROFIT DELIVERY","Planning wireless coverage in an operating building","Treat structure, risers, plant rooms, power and maintenance access as part of the system design."],["PRODUCT SELECTION","How to compare occupancy technologies","Evaluate privacy, field of view, event type, installation constraint and the action the data will support."],["INTEGRATION","Questions to settle before connecting a BMS","Agree ownership, protocol, points, naming, response timing, acceptance tests and fallback behaviour."]];
const resourcesTc = [["業主簡報","如何界定能證明價值的智慧樓宇試點","在選擇設備前先界定一項成果、可靠基準及擴展決定。"],["物業營運","實用樓宇儀表板應顯示甚麼","把狀態、需要注意及行動分開，讓團隊不必解讀原始數據。"],["設計與顧問","私隱優先感測檢查表","讓訊號配合空間，界定永不收集的資料，並記錄處理位置。"],["改造交付","規劃營運中樓宇的無線覆蓋","把結構、槽井、機房、電源及維修通道視為系統設計一部分。"],["產品選擇","如何比較佔用技術","評估私隱、視野、事件類型、安裝限制及數據支援的行動。"],["系統整合","連接 BMS 前需要確認的問題","確認權責、協議、點位、命名、回應時間、驗收測試及後備行為。"]];
const resourcesAr = [["موجز المالك","كيف تحدد تجربة مبنى ذكي تثبت القيمة","حدد نتيجة واحدة وخط أساس موثوقاً وقرار التوسع قبل اختيار الأجهزة."],["تشغيل العقار","ما الذي يجب أن تعرضه لوحة مبنى مفيدة","افصل الحالة وما يحتاج الانتباه والإجراء حتى لا يفسر الفريق القياسات الخام."],["التصميم والاستشارات","قائمة استشعار تبدأ بالخصوصية","طابق الإشارة مع المساحة وحدد ما لا يجمع أبداً ووثق موضع المعالجة."],["تنفيذ التحديث","تخطيط التغطية اللاسلكية في مبنى عامل","اعتبر الهيكل والمجاري وغرف المعدات والطاقة والوصول للصيانة جزءاً من تصميم النظام."],["اختيار المنتج","كيف تقارن تقنيات الإشغال","قيم الخصوصية ومجال الرؤية ونوع الحدث وقيد التركيب والإجراء الذي تدعمه البيانات."],["التكامل","أسئلة قبل ربط BMS","اتفق على المسؤولية والبروتوكول والنقاط والتسمية وزمن الاستجابة واختبارات القبول والسلوك الاحتياطي."]];
const copy={en:{eyebrow:"PRACTICAL KNOWLEDGE",title:<>Specify the outcome.<br/>Then the system.</>,intro:"Short guides for the people responsible for asset value, daily operation and design integrity.",library:"GUIDE LIBRARY",libraryTitle:"Better questions make better buildings.",libraryText:"These topic summaries help teams align before a pilot or project workshop. Ask us for a brief tailored to your property.",request:"Request this guide",resources:resourcesEn},tc:{eyebrow:"實用知識",title:<>先指定成果。<br/>再指定系統。</>,intro:"為負責資產價值、日常營運及設計完整性的團隊而設的精簡指南。",library:"指南資料庫",libraryTitle:"更好的問題，帶來更好的建築。",libraryText:"這些主題摘要協助團隊在試點或項目工作坊前達成共識。你亦可向我們索取按物業需要編寫的簡報。",request:"索取指南",resources:resourcesTc},ar:{eyebrow:"معرفة عملية",title:<>حدد النتيجة.<br/>ثم النظام.</>,intro:"أدلة قصيرة للمسؤولين عن قيمة الأصل والتشغيل اليومي وسلامة التصميم.",library:"مكتبة الأدلة",libraryTitle:"الأسئلة الأفضل تصنع مباني أفضل.",libraryText:"تساعد هذه الملخصات الفرق على الاتفاق قبل تجربة أو ورشة مشروع. اطلب موجزاً مخصصاً لعقارك.",request:"اطلب هذا الدليل",resources:resourcesAr}};
export default async function ResourcesPage({params}:{params?:Promise<{locale?:string}>}={}){const locale=(await params)?.locale;const t=locale==="zh-hant"?copy.tc:locale==="zh-hans"?toSimplified(copy.tc):locale==="ar"?copy.ar:copy.en;return <main className="internal-page"><SiteHeader/><section className="page-hero resources-hero"><div className="page-hero-copy"><p className="eyebrow light">{t.eyebrow}</p><h1>{t.title}</h1><p>{t.intro}</p></div></section><section className="resource-list section-pad"><div className="catalogue-heading"><div><p className="eyebrow">{t.library}</p><h2>{t.libraryTitle}</h2></div><p>{t.libraryText}</p></div><div>{t.resources.map(([label,title,text],i)=><a href={`mailto:enquiry@blutech.io?subject=${encodeURIComponent(title)}`} key={title}><span>{String(i+1).padStart(2,"0")} · {label}</span><h3>{title}</h3><p>{text}</p><b>{t.request} <Arrow/></b></a>)}</div></section><PageCta/><SiteFooter/></main>}
