import type { Metadata } from "next";
import { Arrow, PageCta, SiteFooter, SiteHeader } from "../components/SiteChrome";
import { Localized, LocalizedLink } from "../components/LanguageContext";
import { projects } from "../project-catalogue";
import { localizeProject } from "../project-localization";
import { languageAlternates } from "../localized-metadata";

const projectPriority = ["three-garden-road", "hong-kong-international-airport", "emsd-headquarters", "metroplaza", "hong-kong-west-kowloon-station", "olympian-city", "hospital-patient-safety", "immigration-department-queue-monitoring", "ifc-mall"];
const orderedProjects = [...projects].sort((a, b) => projectPriority.indexOf(a.slug) - projectPriority.indexOf(b.slug));

export const metadata: Metadata = { title:"Building AI and IoT Projects — Blutech", description:"Explore selected Blutech building AI and IoT deployments across commercial property, aviation, healthcare, government and retail.", alternates:{canonical:"/projects",languages:languageAlternates("/projects")} };

export default async function ProjectsPage({ params }: { params?: Promise<{ locale?: string }> } = {}){const locale=(await params)?.locale;const localizedProjects=orderedProjects.map((project)=>localizeProject(project,locale));return <main className="internal-page"><SiteHeader active="projects"/><section className="page-hero project-page-hero"><div className="page-hero-copy"><p className="eyebrow light"><Localized en="SELECTED WORK" tc="精選項目" sc="精选项目" ar="مشاريع مختارة" /></p><h1><Localized en={<>Proven in buildings<br/>that cannot pause.</>} tc={<>在不能停下來的建築中<br/>驗證實力。</>} sc={<>在不能停下来的建筑中<br/>验证实力。</>} ar={<>أداء مثبت في مبانٍ<br/>لا يمكنها التوقف.</>} /></h1><p><Localized en="Offices, aviation, healthcare, retail and public services—each with different operating constraints, connected by the same insistence on useful signals and practical delivery." tc="辦公室、航空、醫療、零售及公共服務，各有不同營運限制，但同樣需要可靠訊號與務實交付。" sc="办公室、航空、医疗、零售及公共服务，各有不同运营限制，但同样需要可靠信号与务实交付。" ar="مكاتب وطيران ورعاية صحية وتجزئة وخدمات عامة؛ بيئات مختلفة يجمعها الاحتياج إلى إشارات مفيدة وتنفيذ عملي." /></p></div></section><section className="work-index section-pad">{localizedProjects.map((project,index)=><LocalizedLink href={`/projects/${project.slug}`} key={project.slug} className="work-card"><div className="work-card-image"><img src={project.image} alt={project.imageAlt || `${project.name} project`}/></div><div className="work-card-copy"><span>{String(index+1).padStart(2,"0")} · {project.sector.toUpperCase()} · {project.location.toUpperCase()}</span><h2>{project.name}</h2><p>{project.summary}</p><b><Localized en="View case study" tc="查看案例" sc="查看案例" ar="عرض دراسة الحالة" /> <Arrow/></b></div></LocalizedLink>)}</section><PageCta/><SiteFooter/></main>}
