import type { Metadata } from "next";
import { languageAlternates } from "../localized-metadata";
import { PageCta, SiteFooter, SiteHeader } from "../components/SiteChrome";
import { toSimplified } from "../project-localization";

const siteUrl = "https://blutech.io";
export const metadata: Metadata = {
  title: "Blutech Halo & Core Building Software",
  description: "Halo gives owners and property teams clear dashboards, floorplans, alerts, reports and work orders. Core connects the devices, data, rules and integrations beneath it.",
  alternates: { canonical: "/software", languages: languageAlternates("/software") },
};

const copy = {
  en: {
    heroLabel:"ONE PLATFORM · TWO PURPOSES", heroTitle:<>Halo for operations.<br/>Core for infrastructure.</>, heroText:"Halo is the daily workspace for owners and property teams. Core is the technical platform beneath it—connecting devices, data, rules, permissions and third-party systems.", haloMap:"See · Decide · Act", coreMap:"Connect · Govern · Integrate", liveData:"LIVE BUILDING DATA",
    haloLabel:"BLUTECH HALO · OPERATIONS", haloTitle:"Everything the property team needs to see. Nothing it does not.", haloText:"Halo turns live building data into a calm daily operating view for owners, property management and facility teams.", haloList:["Portfolio and site overview","Live floorplans and equipment status","Alerts, work orders and escalation","History, trends and scheduled reports","Role-based desktop and mobile access"],
    uiIllustrative:"ILLUSTRATIVE ANONYMISED VIEW", uiOverview:"Operations overview", uiLive:"Live", uiSite:"Site status", uiNormal:"Normal", uiConfigured:"Configured by property", uiActions:"Open actions", uiAssigned:"Assigned", uiWorkflow:"Workflow based", uiComfort:"Comfort", uiTarget:"On target", uiThresholds:"Project thresholds", uiFloor:"Live floor", uiLocation:"LOCATION VIEW", uiHistory:"History", uiTrend:"USAGE TREND",
    coreLabel:"BLUTECH CORE · INFRASTRUCTURE", coreTitle:"One governed layer for devices, data and integration.", coreText:"Core gives technical teams the tools to commission, monitor and integrate the connected building without exposing that complexity to daily users.", coreList:["Device and gateway provisioning","Signal, battery and fleet health","Data models, payloads and permissions","Rules, remote settings and audit history","APIs and building-system integration"],
    deviceEstate:"Device estate", connectedInfrastructure:"Connected infrastructure", devices:"Devices", connected:"Connected", fleetHealth:"Fleet health", monitored:"Monitored", gateways:"Gateways", managed:"Managed", fieldDevice:"FIELD DEVICE", location:"LOCATION", signal:"SIGNAL", state:"STATE", configuredZone:"Configured zone", configuredRoom:"Configured room", assignedGroup:"Assigned group", monitoredZone:"Monitored zone", signalHealth:"Signal health", local:"Local", edgeActive:"Edge active", rule:"RULE", ruleText:"If a long-stay threshold is met → verify event → alert assigned team", active:"Active",
    examplesLabel:"REAL OPERATING VIEWS", examplesTitle:<>One platform.<br/>Many building workflows.</>, examplesText:"Each deployment is configured around the building, user roles and agreed response—not a generic dashboard template.", examples:[["Smart washrooms","Live cubicle status, long-stay events, consumables, cleaning demand and service history."],["Accessible-space safety","Floorplan events and targeted alerts for agreed long-stay, no-motion or safety workflows."],["Indoor air quality","Current conditions, trends, thresholds and reports across rooms, floors or a portfolio."],["Smart lighting","Zone status, schedules, occupied and standby states, device health and energy context."],["Water leakage","Location-aware alarms, escalation and an auditable response record."],["Device estate","Gateway health, signal quality, battery, configuration and installation records."]],
    openLabel:"OPEN BY DEFAULT", openTitle:<>Keep what works.<br/>Connect what matters.</>, openText:"Cloud, private-cloud and on-premise options are coordinated around the project. Final interfaces depend on the installed systems and agreed integration scope.",
  },
  tc: {
    heroLabel:"一個平台 · 兩種用途", heroTitle:<>Halo 支援日常營運。<br/>Core 管理技術基建。</>, heroText:"Halo 是業主及物業團隊的日常工作空間。Core 是其下的技術平台，連接設備、數據、規則、權限及第三方系統。", haloMap:"查看 · 決定 · 行動", coreMap:"連接 · 管理 · 整合", liveData:"即時樓宇數據",
    haloLabel:"BLUTECH HALO · 營運", haloTitle:"讓物業團隊看見所有重要資訊，排除不必要的複雜性。", haloText:"Halo 把即時樓宇數據轉化為業主、物業管理及設施團隊可每天使用的清晰營運視圖。", haloList:["物業組合及單一項目總覽","即時平面圖與設備狀態","警報、工作單與升級流程","歷史、趨勢與定期報告","按角色設定的桌面及手機權限"],
    uiIllustrative:"匿名示意介面", uiOverview:"營運總覽", uiLive:"即時", uiSite:"項目狀態", uiNormal:"正常", uiConfigured:"按物業配置", uiActions:"待處理事項", uiAssigned:"已指派", uiWorkflow:"按流程處理", uiComfort:"舒適度", uiTarget:"符合目標", uiThresholds:"項目門檻", uiFloor:"即時樓層", uiLocation:"位置視圖", uiHistory:"歷史", uiTrend:"使用趨勢",
    coreLabel:"BLUTECH CORE · 技術基建", coreTitle:"統一管理設備、數據與整合。", coreText:"Core 為技術團隊提供配置、監察及整合連接樓宇的工具，同時不把這些複雜性帶給日常使用者。", coreList:["設備與網關配置","訊號、電池與設備健康","數據模型、payload 與權限","規則、遙距設定與審計記錄","API 與樓宇系統整合"],
    deviceEstate:"設備網絡", connectedInfrastructure:"已連接技術基建", devices:"設備", connected:"已連接", fleetHealth:"設備健康", monitored:"受監察", gateways:"網關", managed:"受管理", fieldDevice:"現場設備", location:"位置", signal:"訊號", state:"狀態", configuredZone:"已配置區域", configuredRoom:"已配置房間", assignedGroup:"已指派群組", monitoredZone:"受監察區域", signalHealth:"訊號健康", local:"本地", edgeActive:"邊緣運行", rule:"規則", ruleText:"如達到逗留過久門檻 → 核實事件 → 通知指定團隊", active:"已啟用",
    examplesLabel:"實際營運視圖", examplesTitle:<>一個平台。<br/>多種樓宇流程。</>, examplesText:"每個部署都按樓宇、使用者角色及既定回應配置，而不是套用通用儀表板。", examples:[["智慧洗手間","即時廁格狀態、逗留過久事件、用品水平、清潔需求及服務記錄。"],["無障礙空間安全","平面圖事件及針對既定逗留過久、無動作或安全流程的警報。"],["室內空氣質素","跨房間、樓層或物業組合的即時狀況、趨勢、門檻及報告。"],["智慧照明","區域狀態、時間表、佔用與備用狀態、設備健康及能源背景。"],["漏水監測","帶位置的警報、升級流程及可審計回應記錄。"],["設備網絡","網關健康、訊號質素、電池、配置及安裝記錄。"]],
    openLabel:"預設開放整合", openTitle:<>保留有效系統。<br/>連接重要部分。</>, openText:"雲端、私有雲及現場部署方式按項目協調。最終介面視乎已安裝系統及既定整合範圍。",
  },
  ar: {
    heroLabel:"منصة واحدة · غرضان", heroTitle:<>Halo للتشغيل.<br/>Core للبنية التحتية.</>, heroText:"Halo هو مساحة العمل اليومية للمالكين وفرق العقار. Core هو المنصة التقنية تحته، ويربط الأجهزة والبيانات والقواعد والصلاحيات والأنظمة الخارجية.", haloMap:"شاهد · قرر · نفذ", coreMap:"اربط · نظم · ادمج", liveData:"بيانات المبنى المباشرة",
    haloLabel:"BLUTECH HALO · التشغيل", haloTitle:"كل ما يحتاج فريق العقار إلى رؤيته، بلا تعقيد زائد.", haloText:"يحول Halo بيانات المبنى المباشرة إلى رؤية تشغيل يومية هادئة للمالكين وإدارة العقار وفرق المرافق.", haloList:["نظرة على المحفظة والموقع","مخططات وحالة معدات مباشرة","تنبيهات وأوامر عمل وتصعيد","سجل واتجاهات وتقارير مجدولة","وصول حسب الدور على الحاسوب والهاتف"],
    uiIllustrative:"واجهة توضيحية مجهلة", uiOverview:"نظرة التشغيل", uiLive:"مباشر", uiSite:"حالة الموقع", uiNormal:"طبيعي", uiConfigured:"مهيأ للعقار", uiActions:"الإجراءات المفتوحة", uiAssigned:"مسند", uiWorkflow:"حسب سير العمل", uiComfort:"الراحة", uiTarget:"ضمن الهدف", uiThresholds:"حدود المشروع", uiFloor:"الطابق المباشر", uiLocation:"رؤية الموقع", uiHistory:"السجل", uiTrend:"اتجاه الاستخدام",
    coreLabel:"BLUTECH CORE · البنية التحتية", coreTitle:"طبقة محكومة واحدة للأجهزة والبيانات والتكامل.", coreText:"يمنح Core الفرق التقنية أدوات تهيئة المبنى المتصل ومراقبته ودمجه من دون إظهار هذا التعقيد للمستخدم اليومي.", coreList:["تهيئة الأجهزة والبوابات","الإشارة والبطارية وصحة الأسطول","نماذج البيانات والحمولات والصلاحيات","القواعد والإعدادات عن بعد وسجل التدقيق","واجهات API وتكامل أنظمة المبنى"],
    deviceEstate:"منظومة الأجهزة", connectedInfrastructure:"بنية متصلة", devices:"الأجهزة", connected:"متصلة", fleetHealth:"صحة الأسطول", monitored:"مراقبة", gateways:"البوابات", managed:"مدارة", fieldDevice:"الجهاز الميداني", location:"الموقع", signal:"الإشارة", state:"الحالة", configuredZone:"منطقة مهيأة", configuredRoom:"غرفة مهيأة", assignedGroup:"مجموعة مسندة", monitoredZone:"منطقة مراقبة", signalHealth:"صحة الإشارة", local:"محلي", edgeActive:"الحافة فعالة", rule:"قاعدة", ruleText:"إذا تحقق حد البقاء الطويل ← تحقق من الحدث ← نبه الفريق المعين", active:"فعال",
    examplesLabel:"رؤى تشغيل حقيقية", examplesTitle:<>منصة واحدة.<br/>مسارات مبنى متعددة.</>, examplesText:"يهيأ كل نشر حول المبنى وأدوار المستخدمين والاستجابة المتفق عليها، وليس قالب لوحة عام.", examples:[["دورات المياه الذكية","حالة المقصورات وأحداث البقاء الطويل والمستلزمات وطلب التنظيف وسجل الخدمة."],["سلامة المساحات المهيأة","أحداث المخطط وتنبيهات موجهة لسير عمل البقاء الطويل أو انعدام الحركة أو السلامة."],["جودة الهواء الداخلي","الظروف والاتجاهات والحدود والتقارير عبر الغرف والطوابق أو المحفظة."],["الإضاءة الذكية","حالة المناطق والجداول وحالات الإشغال والاستعداد وصحة الأجهزة وسياق الطاقة."],["تسرب المياه","إنذارات مرتبطة بالموقع وتصعيد وسجل استجابة قابل للتدقيق."],["منظومة الأجهزة","صحة البوابات وجودة الإشارة والبطارية والتهيئة وسجلات التركيب."]],
    openLabel:"مفتوح افتراضياً", openTitle:<>احتفظ بما يعمل.<br/>اربط ما يهم.</>, openText:"تنسق خيارات السحابة والسحابة الخاصة والموقع حسب المشروع. تعتمد الواجهات النهائية على الأنظمة المركبة ونطاق التكامل المتفق عليه.",
  },
};

export default async function SoftwarePage({ params }: { params?: Promise<{ locale?: string }> } = {}) {
  const locale=(await params)?.locale;
  const t=locale==="zh-hant"?copy.tc:locale==="zh-hans"?toSimplified(copy.tc):locale==="ar"?copy.ar:copy.en;
  const data={"@context":"https://schema.org","@type":"SoftwareApplication","@id":`${siteUrl}/software#software`,name:"Blutech Halo and Blutech Core",applicationCategory:"BusinessApplication",operatingSystem:"Web",description:"Building operations dashboard and IoT infrastructure platform for owners, property managers and technical teams.",url:`${siteUrl}/software`,publisher:{"@type":"Organization","@id":`${siteUrl}/#organization`,name:"Blutech"}};
  const rows=[["Thermal sensor",t.configuredZone,t.signalHealth,t.uiNormal],["IAQ sensor",t.configuredRoom,t.signalHealth,t.uiNormal],["Lighting controller",t.assignedGroup,t.local,t.edgeActive],["Leak sensor",t.monitoredZone,t.signalHealth,t.uiNormal]];
  return <main className="internal-page software-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/>
    <SiteHeader active="software"/>
    <section className="page-hero software-hero"><div className="page-hero-copy"><p className="eyebrow light">{t.heroLabel}</p><h1>{t.heroTitle}</h1><p>{t.heroText}</p></div><div className="software-layer-map" aria-hidden="true"><div className="layer-halo"><span>HALO</span><b>{t.haloMap}</b></div><div className="layer-core"><span>CORE</span><b>{t.coreMap}</b></div><i>{t.liveData}</i></div></section>
    <section className="software-product halo-product section-pad"><div className="software-product-copy"><p className="eyebrow">{t.haloLabel}</p><h2>{t.haloTitle}</h2><p>{t.haloText}</p><ul>{t.haloList.map(item=><li key={item}>{item}</li>)}</ul></div><div className="halo-ui" aria-label="Illustrative anonymized Halo operations dashboard"><aside><strong>H</strong><i/><i/><i/><i/><span/></aside><div className="halo-canvas"><header><div><small>{t.uiIllustrative}</small><b>{t.uiOverview}</b></div><span>{t.uiLive}</span></header><div className="halo-kpis"><article><small>{t.uiSite}</small><strong>{t.uiNormal}</strong><em>{t.uiConfigured}</em></article><article><small>{t.uiActions}</small><strong>{t.uiAssigned}</strong><em>{t.uiWorkflow}</em></article><article><small>{t.uiComfort}</small><strong>{t.uiTarget}</strong><em>{t.uiThresholds}</em></article></div><div className="halo-workspace"><section className="halo-floor"><header><b>{t.uiFloor}</b><small>{t.uiLocation}</small></header><div className="floor-shell"><i className="room r1"/><i className="room r2"/><i className="room r3"/><i className="room r4"/><span className="signal s1"/><span className="signal s2"/><span className="signal s3"/><b>{t.uiLive}</b></div></section><section className="halo-activity"><header><b>{t.uiHistory}</b><small>{t.uiTrend}</small></header><svg viewBox="0 0 380 150"><path className="area" d="M0 135 C35 126 52 82 82 91 S130 118 156 68 S208 33 238 76 S295 97 320 51 S355 22 380 38 L380 150 L0 150 Z"/><path className="line" d="M0 135 C35 126 52 82 82 91 S130 118 156 68 S208 33 238 76 S295 97 320 51 S355 22 380 38"/></svg></section></div></div></div></section>
    <section className="software-product core-product section-pad dark-section"><div className="core-ui"><header><div><small>{t.uiIllustrative}</small><b>{t.deviceEstate}</b></div><span>{t.connectedInfrastructure}</span></header><div className="core-summary"><article><small>{t.devices}</small><strong>{t.connected}</strong></article><article><small>{t.fleetHealth}</small><strong>{t.monitored}</strong></article><article><small>{t.gateways}</small><strong>{t.managed}</strong></article></div><div className="core-table"><div><b>{t.fieldDevice}</b><b>{t.location}</b><b>{t.signal}</b><b>{t.state}</b></div>{rows.map(row=><div key={row[0]}>{row.map((cell,index)=><span key={cell} className={index===3?"state":""}>{cell}</span>)}</div>)}</div><footer><span>{t.rule}</span><b>{t.ruleText}</b><i>{t.active}</i></footer></div><div className="software-product-copy"><p className="eyebrow light">{t.coreLabel}</p><h2>{t.coreTitle}</h2><p>{t.coreText}</p><ul>{t.coreList.map(item=><li key={item}>{item}</li>)}</ul></div></section>
    <section className="software-examples section-pad"><div className="catalogue-heading"><div><p className="eyebrow">{t.examplesLabel}</p><h2>{t.examplesTitle}</h2></div><p>{t.examplesText}</p></div><div className="software-example-grid">{t.examples.map(([title,body],index)=><article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="open-stack section-pad"><p className="eyebrow">{t.openLabel}</p><h2>{t.openTitle}</h2><div>{["LoRaWAN","4G","Wi-Fi","Bluetooth","RS485","BACnet","Modbus","MQTT","HTTPS","REST API","Dry contact","On-premise"].map(item=><span key={item}>{item}</span>)}</div><p>{t.openText}</p></section>
    <PageCta/><SiteFooter/>
  </main>;
}
