import type { Metadata } from "next";
import { languageAlternates } from "../localized-metadata";
import { PageCta, SiteFooter, SiteHeader } from "../components/SiteChrome";
import { toSimplified } from "../project-localization";

export const metadata: Metadata = {
  title: "Edge and Cloud Building IoT Technology — Blutech",
  description: "Blutech combines Bluetooth edge control, LoRaWAN building data and 4G or IP backhaul in one connected building platform.",
  alternates: { canonical: "/technology", languages: languageAlternates("/technology") },
};

const copy = {
  en: {
    heroLabel:"FIELD TO SOFTWARE", heroTitle:<>Edge intelligence.<br/>Cloud orchestration.</>, heroText:"Bluetooth keeps time-sensitive control local. LoRaWAN carries building data and settings. 4G or IP gateways connect every layer to Blutech Core—so the building continues to respond and remains centrally manageable.", edge:"EDGE", sense:"Sense", decide:"Decide", control:"Control", cloud:"CLOUD",
    rolesLabel:"THE ROLE OF EACH LAYER", rolesTitle:<>Local when it must respond.<br/>Connected when it must be managed.</>, rolesText:"Many Blutech products use more than one protocol because control, data collection and portfolio management have different technical needs.", roles:[["Bluetooth","Edge control","Fast, direct device-to-device response at the point of use—even without a cloud connection."],["LoRaWAN","Building data","Long-range collection of events, status and measurements, plus remote settings where the product supports downlink."],["4G / IP","Cloud connection","Gateway backhaul through cellular, Ethernet or Wi-Fi into Blutech Core and agreed third-party systems."],["Core","Orchestration","One governed layer for devices, data, rules, permissions, history and integrations across every protocol."]],
    connectedLabel:"ONE CONNECTED BUILDING", connectedTitle:<>Independent at the edge.<br/>Coordinated in Core.</>, connectedText:"Local logic handles the immediate event. The connected layer provides common data, remote settings, governance and integration across products and properties.", path:[["Field event","Occupancy, air, water, door, equipment or schedule."],["Edge response","Bluetooth or wired logic acts immediately where required."],["Building network","LoRaWAN gathers status and data across the property."],["Core & Halo","4G or IP backhaul enables management, insight and workflows."]],
    examplesLabel:"HOW PRODUCTS WORK TOGETHER", examplesTitle:<>Designed as a system,<br/>not a collection of boxes.</>, examplesText:"The protocol mix is selected around response time, coverage, resilience, existing infrastructure and the operating brief.", examples:[["Smart lighting","A BT321 PIR can trigger its assigned Bluetooth lighting group locally. LoRaWAN carries status and settings through a 4G or IP gateway to Core."],["Field control","BT315 and BT316 combine local Bluetooth logic with LoRaWAN events and remote configuration for dependable on-site response."],["Vacancy indication","A nearby door or occupancy sensor can change BT2035 immediately over Bluetooth while LoRaWAN shares the current status."],["Building sensing","Indoor air quality, HeatMap and water-leakage devices send useful building data over LoRaWAN through the selected gateway backhaul."]],
    aiLabel:"AI WHERE IT EARNS ITS PLACE", aiTitle:"Intelligence with a clear job.", aiText:"AI belongs where it improves the reliability or usefulness of a building signal. Deterministic rules remain the better choice where they are simpler, clearer and sufficient.", aiList:["Edge processing for privacy and response","Historical context for useful anomalies","Human-readable rules and workflows","Verified outcomes before portfolio scale"],
  },
  tc: {
    heroLabel:"由現場到軟件", heroTitle:<>邊緣智能。<br/>雲端協調。</>, heroText:"Bluetooth 把需要即時回應的控制留在現場。LoRaWAN 傳送樓宇數據與設定。4G 或 IP 網關把各層連接至 Blutech Core，讓樓宇持續回應並可中央管理。", edge:"邊緣", sense:"感測", decide:"判斷", control:"控制", cloud:"雲端",
    rolesLabel:"每一層的角色", rolesTitle:<>需要回應時留在本地。<br/>需要管理時保持連接。</>, rolesText:"不少 Blutech 產品使用多於一種協議，因為控制、數據收集及物業組合管理有不同技術需要。", roles:[["Bluetooth","邊緣控制","即使沒有雲端連接，設備亦可在使用位置快速直接回應。"],["LoRaWAN","樓宇數據","長距離收集事件、狀態與量度數據；產品支援下行時亦可遙距設定。"],["4G / IP","雲端連接","網關透過流動網絡、Ethernet 或 Wi-Fi 連接 Blutech Core 及既定第三方系統。"],["Core","系統協調","跨協議統一管理設備、數據、規則、權限、歷史及整合。"]],
    connectedLabel:"一棟連接樓宇", connectedTitle:<>邊緣獨立運作。<br/>Core 統一協調。</>, connectedText:"本地邏輯處理即時事件；連接層在產品與物業之間提供共同數據、遙距設定、治理與整合。", path:[["現場事件","佔用、空氣、水、門、設備或時間表。"],["邊緣回應","Bluetooth 或有線邏輯在需要時即時行動。"],["樓宇網絡","LoRaWAN 在物業內收集狀態與數據。"],["Core 與 Halo","4G 或 IP 上行連接支援管理、洞察與流程。"]],
    examplesLabel:"產品如何協同運作", examplesTitle:<>作為一個系統設計，<br/>而不是設備組合。</>, examplesText:"協議組合按回應時間、覆蓋、韌性、既有基建及營運要求選擇。", examples:[["智慧照明","BT321 PIR 可在本地觸發指定 Bluetooth 照明群組；LoRaWAN 經 4G 或 IP 網關把狀態與設定送到 Core。"],["現場控制","BT315 與 BT316 結合本地 Bluetooth 邏輯、LoRaWAN 事件及遙距配置，提供可靠現場回應。"],["可用狀態指示","附近的門或佔用感測器可經 Bluetooth 即時改變 BT2035，而 LoRaWAN 分享目前狀態。"],["樓宇感測","空氣質素、HeatMap 及漏水設備透過 LoRaWAN 和所選網關上行連接傳送樓宇數據。"]],
    aiLabel:"只在真正有價值的位置使用 AI", aiTitle:"每一項智能，都有清晰任務。", aiText:"AI 應用於能提升樓宇訊號可靠性或實用性的地方；如確定性規則更簡單、清楚而且足夠，就應採用規則。", aiList:["邊緣處理保障私隱及即時回應","以歷史背景判斷有用異常","人員可理解的規則與流程","先驗證成果，再擴展至物業組合"],
  },
  ar: {
    heroLabel:"من الموقع إلى البرمجيات", heroTitle:<>ذكاء الحافة.<br/>تنسيق السحابة.</>, heroText:"يبقي Bluetooth التحكم الحساس للوقت محلياً. يحمل LoRaWAN بيانات المبنى وإعداداته. تربط بوابات 4G أو IP كل طبقة بـBlutech Core، فيستمر المبنى في الاستجابة ويبقى قابلاً للإدارة مركزياً.", edge:"الحافة", sense:"استشعر", decide:"قرر", control:"تحكم", cloud:"السحابة",
    rolesLabel:"دور كل طبقة", rolesTitle:<>محلي عندما يجب أن يستجيب.<br/>متصل عندما يجب أن يدار.</>, rolesText:"تستخدم منتجات Blutech عدة بروتوكولات لأن التحكم وجمع البيانات وإدارة المحفظة لها احتياجات تقنية مختلفة.", roles:[["Bluetooth","تحكم الحافة","استجابة سريعة ومباشرة بين الأجهزة عند نقطة الاستخدام حتى من دون اتصال سحابي."],["LoRaWAN","بيانات المبنى","جمع بعيد المدى للأحداث والحالة والقياسات، مع إعدادات عن بعد عندما يدعم المنتج الوصلة الهابطة."],["4G / IP","اتصال السحابة","ربط البوابة عبر الشبكة الخلوية أو Ethernet أو Wi-Fi إلى Blutech Core والأنظمة الخارجية المتفق عليها."],["Core","التنسيق","طبقة محكومة للأجهزة والبيانات والقواعد والصلاحيات والسجل والتكامل عبر البروتوكولات."]],
    connectedLabel:"مبنى واحد متصل", connectedTitle:<>مستقل عند الحافة.<br/>منسق في Core.</>, connectedText:"يعالج المنطق المحلي الحدث الفوري، وتوفر الطبقة المتصلة بيانات مشتركة وإعدادات عن بعد وحوكمة وتكاملاً عبر المنتجات والعقارات.", path:[["حدث ميداني","إشغال أو هواء أو ماء أو باب أو معدات أو جدول."],["استجابة الحافة","ينفذ Bluetooth أو المنطق السلكي فوراً حيث يلزم."],["شبكة المبنى","يجمع LoRaWAN الحالة والبيانات عبر العقار."],["Core وHalo","يتيح ربط 4G أو IP الإدارة والرؤية وسير العمل."]],
    examplesLabel:"كيف تعمل المنتجات معاً", examplesTitle:<>مصمم كنظام،<br/>لا كمجموعة صناديق.</>, examplesText:"يختار مزيج البروتوكولات حسب زمن الاستجابة والتغطية والمرونة والبنية القائمة والموجز التشغيلي.", examples:[["الإضاءة الذكية","يمكن لـBT321 PIR تشغيل مجموعة Bluetooth محلياً، بينما يحمل LoRaWAN الحالة والإعدادات عبر بوابة 4G أو IP إلى Core."],["التحكم الميداني","يجمع BT315 وBT316 منطق Bluetooth المحلي وأحداث LoRaWAN والتهيئة عن بعد لاستجابة موثوقة في الموقع."],["بيان التوافر","يمكن لمستشعر باب أو إشغال قريب تغيير BT2035 فوراً عبر Bluetooth بينما يشارك LoRaWAN الحالة."],["استشعار المبنى","ترسل أجهزة جودة الهواء وHeatMap وتسرب المياه بيانات مفيدة عبر LoRaWAN والربط المختار للبوابة."]],
    aiLabel:"AI حيث يثبت قيمته", aiTitle:"ذكاء بمهمة واضحة.", aiText:"ينتمي AI إلى المواضع التي يحسن فيها موثوقية إشارة المبنى أو فائدتها. تبقى القواعد المحددة أفضل عندما تكون أبسط وأوضح وكافية.", aiList:["معالجة الحافة للخصوصية والاستجابة","سياق تاريخي للشذوذ المفيد","قواعد وسير عمل مفهومة للبشر","نتائج مثبتة قبل التوسع عبر المحفظة"],
  },
};

export default async function TechnologyPage({ params }: { params?: Promise<{ locale?: string }> } = {}) {
  const locale=(await params)?.locale;
  const t=locale==="zh-hant"?copy.tc:locale==="zh-hans"?toSimplified(copy.tc):locale==="ar"?copy.ar:copy.en;
  return <main className="internal-page technology-page"><SiteHeader active="technology"/>
    <section className="page-hero tech-hero"><div className="page-hero-copy"><p className="eyebrow light">{t.heroLabel}</p><h1>{t.heroTitle}</h1><p>{t.heroText}</p></div><div className="edge-cloud-visual" aria-hidden="true"><div><span>{t.edge}</span><b>{t.sense}</b><b>{t.decide}</b><b>{t.control}</b></div><i><small>LoRaWAN</small><small>4G / IP</small></i><div><span>{t.cloud}</span><b>Core</b><em>Halo</em></div></div></section>
    <section className="protocol-roles section-pad"><div className="catalogue-heading"><div><p className="eyebrow">{t.rolesLabel}</p><h2>{t.rolesTitle}</h2></div><p>{t.rolesText}</p></div><div className="protocol-role-grid">{t.roles.map(([protocol,role,body],index)=><article key={protocol}><span>{String(index+1).padStart(2,"0")}</span><small>{role}</small><h3>{protocol}</h3><p>{body}</p></article>)}</div></section>
    <section className="connected-architecture section-pad dark-section"><div><p className="eyebrow light">{t.connectedLabel}</p><h2>{t.connectedTitle}</h2><p>{t.connectedText}</p></div><ol>{t.path.map(([title,body],index)=><li key={title}><span>{String(index+1).padStart(2,"0")}</span><b>{title}</b><p>{body}</p></li>)}</ol></section>
    <section className="technology-examples section-pad"><div className="catalogue-heading"><div><p className="eyebrow">{t.examplesLabel}</p><h2>{t.examplesTitle}</h2></div><p>{t.examplesText}</p></div><div className="technology-example-grid">{t.examples.map(([title,body],index)=><article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="ai-selective dark-section section-pad"><div><p className="eyebrow light">{t.aiLabel}</p><h2>{t.aiTitle}</h2></div><div><p>{t.aiText}</p><ul>{t.aiList.map(item=><li key={item}>{item}</li>)}</ul></div></section>
    <PageCta/><SiteFooter/>
  </main>;
}
